name: Java CI with Gradle

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jdk_version: [11, 17, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.jdk_version }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk_version }}
      id: setup-java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk_version }}
        distribution: 'temurin'
    - name: Download hsdis for windows-x86_64
      if: ${{ matrix.os == 'windows-latest' }}
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
          url: https://chriswhocodes.com/hsdis/hsdis-amd64.dll
          target: ${{ steps.setup-java.outputs.path }}\\bin
    - name: Download hsdis for linux-x86_64
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
          url: https://chriswhocodes.com/hsdis/hsdis-amd64.so
          target: ${{ steps.setup-java.outputs.path }}/lib
    - name: Download hsdis for macos-x86_64
      if: ${{ matrix.os == 'macos-latest' }}
      uses: suisei-cn/actions-download-file@v1.3.0
      with:
          url: https://chriswhocodes.com/hsdis/hsdis-amd64.dylib
          target: ${{ steps.setup-java.outputs.path }}/lib
    - name: Build with Gradle
      run: |
        ./gradlew clean test build --stacktrace
    
